# Generated by Django 3.2.5 on 2021-07-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='big_sister',
            field=models.CharField(default='Joy Kamureni', max_length=20),
        ),
        migrations.AddField(
            model_name='students',
            name='class_name',
            field=models.CharField(default='Anita B', max_length=10),
        ),
        migrations.AddField(
            model_name='students',
            name='county_or_district',
            field=models.CharField(default='Kanungu', max_length=15),
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default='anyijukirjanett@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], default='female', max_length=1),
        ),
        migrations.AddField(
            model_name='students',
            name='id_number',
            field=models.CharField(default=5343, max_length=20),
        ),
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='students',
            name='medical_form',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='students',
            name='mentor',
            field=models.CharField(default='Sylvia Mbugua', max_length=29),
        ),
        migrations.AddField(
            model_name='students',
            name='nationality',
            field=models.CharField(default='Ugandan', max_length=15),
        ),
        migrations.AddField(
            model_name='students',
            name='passport_number',
            field=models.CharField(default=3445, max_length=20),
        ),
        migrations.AddField(
            model_name='students',
            name='room_number',
            field=models.CharField(default=12, max_length=5),
        ),
    ]
