# Generated by Django 3.2.5 on 2021-09-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210813_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='county_or_district',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, default='anyijukirjanett@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], default='female', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_number',
            field=models.CharField(blank=True, default=5343, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='students',
            name='medical_form',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='nationality',
            field=models.CharField(blank=True, default='Ugandan', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='passport_number',
            field=models.CharField(blank=True, default=3445, max_length=20, null=True),
        ),
    ]
