# Generated by Django 3.2.5 on 2021-08-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(default='myemai@gmail.com', max_length=254)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('profession', models.CharField(default='CTO', max_length=15)),
                ('company', models.CharField(default='Sky Garden', max_length=15)),
                ('job_title', models.CharField(default='Backend Developer', max_length=25)),
                ('course', models.CharField(default='Backend deveelopment', max_length=30)),
                ('lessons_attendance', models.CharField(default='10', max_length=15)),
                ('resume', models.FileField(default='Resume.pdf', upload_to='')),
                ('nationality', models.CharField(default='Kenyan', max_length=15)),
                ('contract', models.FileField(default='default.pdf', upload_to='')),
                ('syllabus', models.CharField(default='sylabus', max_length=15)),
                ('id_Number', models.CharField(default='263634', max_length=20)),
            ],
        ),
    ]
