# Generated by Django 3.2.6 on 2021-08-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='course',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='company',
            field=models.CharField(help_text='company', max_length=15),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='id_Number',
            field=models.CharField(help_text='123456', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='job_title',
            field=models.CharField(help_text='eg SOftware Engineer', max_length=25),
        ),
    ]
