# Generated by Django 3.2.5 on 2021-09-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20210827_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='images_6.jpeg', upload_to=''),
        ),
    ]
