# Generated by Django 3.2.5 on 2021-09-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_trainer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='company',
            field=models.CharField(blank=True, help_text='company', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='id_Number',
            field=models.CharField(blank=True, help_text='123456', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='job_title',
            field=models.CharField(blank=True, help_text='eg SOftware Engineer', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='lessons_attendance',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='nationality',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profession',
            field=models.CharField(blank=True, default='CTO', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='syllabus',
            field=models.CharField(blank=True, default='sylabus', max_length=15, null=True),
        ),
    ]
