# Generated by Django 3.2.5 on 2021-09-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, default='2021-07-04 00:00', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_activity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_planner_or_organiser',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.CharField(blank=True, help_text='eg Bool', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_attendees',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='signed_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, default='2021-07-04 00:00', null=True),
        ),
    ]
