# Generated by Django 3.2.5 on 2021-08-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=15)),
                ('unit_code', models.CharField(max_length=10)),
                ('duration', models.DateTimeField()),
                ('trainers_name', models.CharField(default='your name', max_length=30)),
                ('course_syllabus', models.CharField(default='Back end development', max_length=30)),
                ('course_material', models.CharField(default='youtube', max_length=30)),
            ],
        ),
    ]
