# Generated by Django 3.2.5 on 2021-09-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_material',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_syllabus',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='trainers_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
